---
title: "Demo in Chinses-language Texts"
author: Haiyan Wang
output: 
    rmarkdown::html_vignette:
        css: mystyle.css
        toc: yes
vignette: >
  %\VignetteIndexEntry{Demo in Chinese}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

---
title: "Application of quanteda: Chinese"
date: "27/11/2017"
---

## Chinese Stop words: Baidu Stopwords
```{r}
require(readtext)
require(stringi)
require(quanteda)

#read Chinese stop words
csw <- stopwords("chinese")

# an example of using csw
tokens_select(tokens("中华人民共和国成立于1949 年"), csw, selection = "remove")
```

## Example application on a set of text files in Chinese

49 "REPORT ON THE WORK OF THE GOVERNMENT" by Premier of the State Council, 1954 - 2017 
```{r fig1, fig.height = 5, fig.width = 5, fig.align = "center"}
#read text files
data(data_corpus_chinesegovreport)
head(summary(ch_gov_Corpus))

#tokenize
chtoks <- tokens(ch_gov_Corpus, remove_punct = TRUE)
chtoks <- tokens_remove(chtoks, stopwords("chinese"))

#dfm
chdfm <- dfm(chtoks)
topfeatures(chdfm)
#发展 经济 社会 建设 改革 人民 主义 工作 企业 国家 
#5627 5036 4255 4248 2931 2897 2817 2642 2627 2595 

# plot a word cloud
set.seed(100)
chdfm_tf <- dfm_trim(chdfm, min_count = 500)
par(family = "STKaiti") # "楷体“ this line is necessary for Mac
textplot_wordcloud(chdfm_tf, min.freq = 6, random.order = FALSE,
                   rot.per = .25, max.words = 100, scale = c(2.8, .5),
                   colors = RColorBrewer::brewer.pal(8,"Dark2"))
```

### Feature co-occurrence matrix
```{r}
#fcm within the window size of 5
ch17txt <- corpus_subset(ch_gov_Corpus, Year == "2017")
ch17toks <- tokens(ch17txt, remove_punct = TRUE)
ch17toks <- tokens_remove(ch17toks, stopwords("chinese"))
chfcm <- fcm(ch17toks, context = "window")  
topfeatures(chfcm["改革", ])

# fcm within window: "改革"+ “xx”
chfcm <- fcm(ch17toks, context = "window", ordered = TRUE, tri = FALSE)  # default window size = 5
topfeatures(chfcm["改革", ])
```

### Scaling Model
```{r fig2, fig.height = 4, fig.width = 6, fig.align = "center"}
wfm <- textmodel_wordfish(chdfm)
y <- 1954:2017
y <- y[-which(y==1963 | y==1961 |y==1962 | (y>1964 & y<1975) | y==1976 |y==1977)]
plot(y, wfm@theta, xlab = "Year", ylab = "Position")
```

### Collocations - bigrams/trigrams etc. 
```{r}
#bigrams cross the whole dataset
ch_mw <- textstat_collocations(chtoks, size = 2, min_count = 20, tolower = TRUE)
head(ch_mw, 10)

# bigrams in 2017 report
ch_mw17 <- textstat_collocations(ch17toks, size = 2, tolower = TRUE)
head(ch_mw17, 10)
```
