---
title: "Replication: Text Analysis with R for Students of Literature"
author: Kenneth Benoit, Stefan Müller, and Paul Nulty
output: 
  html_document:
    toc: true
---

```{r message=FALSE}
library("quanteda")
library("stringi")
load("data_char_mobydick.rda")
```

```{r}
# extract the header information
start_v <- stri_locate_first_fixed(data_char_mobydick, "CHAPTER 1. Loomings.")[1]
end_v <- stri_locate_last_fixed(data_char_mobydick, "orphan.")[1]
txt <- stri_sub(data_char_mobydick, start_v, end_v)
```

```{r}
toks <- tokens(txt)
toks_lower <- tokens_tolower(toks)
```

```{r}
xtoks <- as.tokens_xptr(toks)
type <- quanteda:::cpp_get_types(xtoks)
pat <- "whale*"
```

```{r, eval=FALSE}
quanteda_options(threads = 2)
out <- quanteda:::index_types(pat, type, "glob")
```

```{r, eval=FALSE}
conc <- attributes(xtoks)$meta$object$concatenator
ids <- object2id(pat, type, case_insensitive = TRUE, concatenator = conc)
print(ids)
head(quanteda:::cpp_index(xtoks, ids))
```

```{r, eval=TRUE}
#ERROR?
nrow(index(toks_lower, pattern = "whale"))
nrow(index(toks_lower, pattern = "whale*")) # includes words like "whalemen"
```

```{r, eval=FALSE}
# same thing using kwic()
nrow(kwic(toks_lower, pattern = "whale"))
nrow(kwic(toks_lower, pattern = "whale*")) # includes words like "whalemen"
```
