---
title: "Example: word embedding (gloVe/word2vec)"
author: Kenneth Benoit, Haiyan Wang and Kohei Watanabe
output: 
  rmarkdown::html_vignette:
    toc: no
    number_sections: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = FALSE, 
                      comment = "##")
```

    
```{r, message = FALSE}
library(quanteda)
```

This is intended to show how **quanteda** can be used with the [**text2vec**](http://text2vec.org) package in order to replicate its [gloVe example](http://text2vec.org/glove.html).

Reading the corpus from the [**text2vec** vignette](http://text2vec.org/glove.html):
```{r eval = TRUE}
temp_file <- '/tmp/wiki.RDS'
if (!file.exists(temp_file)) {
    wiki <- corpus(readtext::readtext("http://mattmahoney.net/dc/text8.zip", verbosity = 0))
    saveRDS(wiki, file = paste0(temp_file))
} else {
    wiki <- readRDS(paste0(temp_file))
}
```

Trimming the features before constructing the fcm:
```{r}
wiki_dfm <- dfm(wiki, verbose = TRUE)
feat <- featnames(dfm_trim(wiki_dfm, min_count = 5, verbose = TRUE))
wiki_toks <- tokens(wiki) %>% tokens_select(feat, padding = TRUE)
```

Constructing the fcm:
```{r}
wiki_fcm <- fcm(wiki_toks, context = "window", count = "weighted", weights = 1/(1:5), tri = TRUE)
```

More coming soon!


