\documentclass{article}
%\VignetteIndexEntry{quanteda}
\title{Quanteda Package Vignette Testing}
\author{Kenneth Benoit and Paul Nulty}
\begin{document}

\maketitle


\section{It's just like a latex file}
The document should be written and interpreted as a latex file.

% R code chunks start with this symbol <<>>= and end with @
<<>>=
x <- 5
y <- 9
z <- x * y
print("testing")
print(z)
@
\end{document}
