---
title: "Using quanteda with text2vec"
author: Kenneth Benoit, Haiyan Wang
output: rmarkdown::html_vignette
toc: no
vignette: >
    %\VignetteIndexEntry{Using quanteda with text2vec}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---
    
```{r echo = FALSE}
library("quanteda")
```

Reading the corpus from the [**text2vec** vignette](http://text2vec.org/glove.html):
```{r eval = TRUE}
temp_file <- tempfile()
if (!file.exists(temp_file)) {
    wiki <- corpus(readtext::readtext("http://mattmahoney.net/dc/text8.zip", verbosity = 0))
    saveRDS(wiki, file = paste0(temp_file, '.RDA'))
} else {
    wiki <- readRDS(paste0(temp_file, '.RDA'))
}
```
(for local use, you should execute that once, and then save the object as `~/tmp/wiki.RData`.)

Trimming the features before constructing the fcm:
```{r}
wiki_dfm <- dfm(wiki, verbose = TRUE)
features_to_keep <- featnames(dfm_trim(wiki_dfm, min_count = 5, verbose = TRUE))
wiki_toks <- tokens(wiki) %>% tokens_select(features_to_keep, padding = TRUE)
```
Constructing the fcm:
```{r}
qtcm <- fcm(wiki_toks, context = "window", count = "weighted", weights = 1/(1:5), tri = TRUE)
```



