---
title: "Hackathon for CRAN launch Plan"
author: "Ken Benoit"
date: "10 February 2015"
output: html_document
---

## General Idea

Sustained, concerted programming effort in an interactive environment, to smooth out remaining
kinks necessary to submit quanteda to CRAN with a 0.80 version number.

## How

You can follow this workflow for each set of major change you will work on.

1. Coordinate with Paul which task you will address first.  This is to prevent merge conflicts
   wherein multiple people work on the same source code file.
2. Create a branch off of `dev` that you will work on.  Ask PN if you need help with this.
3. PN/KB will review your changes and merge into `dev` following review, and delete the branch.

Any questions, ask Paul or Ken.

## Tasks and To-Dos

**Team:** KB = Ken Benoit; 
PB = Pablo Barbera;
PN = Paul Nulty; 
KW = Kohei Watanabe; 
BL = Ben Lauderdale; 
SM = Slava Mikhaylov

### KB

- tidy up `dfm` source code, especially new S4 parts
- S4 method for `textmodel`
- get `settings` working
- integrate BL's wordfish into new `textmodel` structure
- review DESCRIPTION::Imports to see if we can reduce package dependencies
- ellipsis argument checking and error catching

### PN

- vignette(s)
- performance profilng for `clean`/`tokenize`
- source code, syntax review
- check demos

### BL

- wordfish Cpp

### KW (and SM if available)

- use case tests
- stress tests: try to break quanteda!
- examine all documentation and vignettes for errors

### PB

- review Facebook and Twitter functions, ensure documentation is complete

### All

- general source code sweep
- command syntax review
- check pdf documentation

## If we have time

- kNN

