// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// index_cpp
Rcpp::List index_cpp(SEXP x, const std::vector< std::string >& types, const int& n);
RcppExport SEXP quanteda_index_cpp(SEXP xSEXP, SEXP typesSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::string >& >::type types(typesSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    __result = Rcpp::wrap(index_cpp(x, types, n));
    return __result;
END_RCPP
}
// skipgramcpp
StringVector skipgramcpp(std::vector < std::string > tokens, std::vector < int > ns, std::vector < int > ks, std::string delim);
RcppExport SEXP quanteda_skipgramcpp(SEXP tokensSEXP, SEXP nsSEXP, SEXP ksSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type tokens(tokensSEXP);
    Rcpp::traits::input_parameter< std::vector < int > >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< std::vector < int > >::type ks(ksSEXP);
    Rcpp::traits::input_parameter< std::string >::type delim(delimSEXP);
    __result = Rcpp::wrap(skipgramcpp(tokens, ns, ks, delim));
    return __result;
END_RCPP
}
// find_sequence_cppl
Rcpp::List find_sequence_cppl(SEXP x, const std::vector<std::string>& types, const int& count_min, const int& len_max, const double& smooth);
RcppExport SEXP quanteda_find_sequence_cppl(SEXP xSEXP, SEXP typesSEXP, SEXP count_minSEXP, SEXP len_maxSEXP, SEXP smoothSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type types(typesSEXP);
    Rcpp::traits::input_parameter< const int& >::type count_min(count_minSEXP);
    Rcpp::traits::input_parameter< const int& >::type len_max(len_maxSEXP);
    Rcpp::traits::input_parameter< const double& >::type smooth(smoothSEXP);
    __result = Rcpp::wrap(find_sequence_cppl(x, types, count_min, len_max, smooth));
    return __result;
END_RCPP
}
// join_tokens_cpp
StringVector join_tokens_cpp(SEXP x, const std::vector<std::string>& tokens_join, const std::string& delim);
RcppExport SEXP quanteda_join_tokens_cpp(SEXP xSEXP, SEXP tokens_joinSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type tokens_join(tokens_joinSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type delim(delimSEXP);
    __result = Rcpp::wrap(join_tokens_cpp(x, tokens_join, delim));
    return __result;
END_RCPP
}
// join_tokens_cppl
List join_tokens_cppl(SEXP x, const std::vector<bool>& flag, const std::vector<std::string>& tokens_join, const std::string& delim);
RcppExport SEXP quanteda_join_tokens_cppl(SEXP xSEXP, SEXP flagSEXP, SEXP tokens_joinSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector<bool>& >::type flag(flagSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type tokens_join(tokens_joinSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type delim(delimSEXP);
    __result = Rcpp::wrap(join_tokens_cppl(x, flag, tokens_join, delim));
    return __result;
END_RCPP
}
// select_tokens_cppl
Rcpp::List select_tokens_cppl(SEXP x, const std::vector< std::string >& types, const bool& remove, const bool& spacer);
RcppExport SEXP quanteda_select_tokens_cppl(SEXP xSEXP, SEXP typesSEXP, SEXP removeSEXP, SEXP spacerSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::vector< std::string >& >::type types(typesSEXP);
    Rcpp::traits::input_parameter< const bool& >::type remove(removeSEXP);
    Rcpp::traits::input_parameter< const bool& >::type spacer(spacerSEXP);
    __result = Rcpp::wrap(select_tokens_cppl(x, types, remove, spacer));
    return __result;
END_RCPP
}
// wordfishcpp
Rcpp::List wordfishcpp(SEXP wfm, SEXP dir, SEXP priors, SEXP tol, SEXP disp, SEXP dispfloor);
RcppExport SEXP quanteda_wordfishcpp(SEXP wfmSEXP, SEXP dirSEXP, SEXP priorsSEXP, SEXP tolSEXP, SEXP dispSEXP, SEXP dispfloorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type wfm(wfmSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< SEXP >::type priors(priorsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type disp(dispSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dispfloor(dispfloorSEXP);
    __result = Rcpp::wrap(wordfishcpp(wfm, dir, priors, tol, disp, dispfloor));
    return __result;
END_RCPP
}
