---
title: "事例: 2017年総選挙に関するツイート"
author: Kohei Watanabe and Akitaka Matsuo
output: 
  html_document:
    toc: true
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "##"
)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## パッケージの読み込み
```{r, message = FALSE}
devtools::install_github("quanteda/quanteda.data")
library(quanteda)
library(quanteda.data)
library(stringi)
```


## 安倍晋三についてツイッターコーパスをダウンロード
等で
```{r}
corp <- data_download(url = 'https://www.dropbox.com/s/co12wpj08pzqz71/data_corpus_election2017tweets.rds?dl=1')
texts(corp) <- stri_trans_nfkc(texts(corp))


```


## 投稿の数と期間を取得
```{r}
ndoc(corp)
range(docvars(corp, 'created_at'))
```


# 前処理

## 語の分割と結合

```{r}

toks <- tokens(corp, remove_separator = FALSE, remove_url = TRUE)
toks <- tokens_remove(toks, '^[\\b\\s]+$', valuetype = 'regex', padding = TRUE)

head(toks)
#toks <- tokens_select(toks, '^[\\w#@]+$', valuetype = 'regex', padding = TRUE)
#toks <- tokens_remove(toks, '^[:hira:]$', valuetype = 'regex', padding = TRUE)

toks_hira <- tokens_keep(toks, '^[:hira:]+$', valuetype = 'regex', padding = TRUE)
col_hira <- textstat_collocations(toks_hira, min_count = 10, size = 2)

stop <- featnames(dfm_trim(dfm(toks_hira), min_docfreq = 0.05))

toks <- tokens_remove(toks, stop, padding = TRUE)
toks <- tokens_compound(toks, col_hira[col_hira$z > 3,], concatenator = '')

#toks <- tokens_remove(toks, feat, valuetype = 'fixed', padding = TRUE)
#toks <- tokens_remove(toks, '\\W', valuetype = 'regex', padding = TRUE)


col <- textstat_collocations(toks, min_count = 10)
#col <- col[stri_detect_regex(col$collocation, '([:number:]|[:kana:]|[:han:])'),]
toks <- tokens_compound(toks, col[col$z > 3,], concatenator = '')

#toks2 <- tokens_compound(toks, col[col$z > 3,], concatenator = '', join = FALSE)
toks <- tokens_compound(toks, phrase('# *'), concatenator = '')
mt <- dfm(toks)
```

```{r}
mt_tag <- dfm_select(mt, '#*')
mt_tag <- dfm_remove(mt_tag, c('*選挙*', '*衆院選*', '*衆議院*', '*投票*'))

mt_tag <- dfm_select(mt_tag, min_nchar = 2)
mt_tag <- dfm_trim(mt_tag, min_count = 10)
mt_co <- fcm(mt_tag)
feat <- names(topfeatures(mt_co, 100))
textplot_network(fcm_select(mt_co,  feat), min_freq = 0.8)
```

```{r}
mt_msg <- dfm_remove(mt, c('#*', '@*'))
mt_msg <- dfm_remove(mt_msg, '^[ぁ-ん]+$', 'regex')

mt_msg <- dfm_select(mt_msg, min_nchar = 2)
mt_msg <- dfm_trim(mt_msg, min_count = 10)
mt_co <- fcm(mt_msg)
feat <- names(topfeatures(mt_co, 100))
textplot_network(fcm_select(mt_co,  feat), min_freq = 0.7)

```

