
cleanSingle <- function(s, removeDigits=TRUE, removePunct=TRUE, lower=TRUE,
                        additional=NULL, twitter=FALSE) {

    s <- gsub("_", "undeeerscoooore", s)
    
    if (twitter) {
        s <- gsub("#", "hhaasshh", s)
        s <- gsub("@", "aattssiiggnn", s)
    }
    if (removePunct) {
        s <- gsub("[[:punct:]]", "", s)
    }
    
    # remove punctuation, plus any additional characters
#     remove <- paste("\\]|[$%&'/;`~!\"\\(\\)\\*\\+\\,\\.\\:\\<\\=\\>\\?\\[\\^\\{\\|\\}",
#                     # only remove if twitter=FALSE
#                     ifelse(!twitter, "#@]", "]"),  
#                     # for additional grep elements
#                     ifelse(!is.null(additional), paste("|", additional, sep=""), ""),
#                     "|\\-",  # this has to go last
#                     sep="")
#     print(remove)
#     
    # must remove "punctuation" first
    if (removeDigits) {
        s <- gsub("[[:digit:]]", "", s)
    } 
    if (lower) {
        s <- tolower(s)
    }

    if (twitter) {
        s <- gsub("hhaasshh", "#", s)
        s <- gsub("aattssiiggnn", "@", s)
    }
    s <- gsub("undeeerscoooore", "_", s)
    if (!is.null(additional)) {
        s <- gsub(additional, "", s)
    }

    # convert 2+ multiple whitespaces into one
    # s <- gsub("\\s{2,}", " ", s)
    # remove leading and trailing whitespace and return, plus additional
    gsub("^ +| +$", "", s)
}

#' simple cleaning of text before processing
#' 
#' \code{clean} removes punctuation and digits from text, using the regex 
#' character classes for punctuation and digits. \code{clean} uses the standard R
#' function \code{tolower} to convert the text to lower case. Each of these 
#' steps is optional, but switched on by default, so for example, to remove 
#' punctuation and convert to lower, but keep digits, the command would be: 
#' \code{clean(mytexts, removeDigits=FALSE)}
#' @rdname clean
#' @param x The object to be cleaned. Can be either a character vector or a 
#'   corpus object. If x is a corpus, \code{clean} returns a copy of the x with 
#'   the texts cleaned.
#' @param removeDigits remove numbers if \code{TRUE}
#' @param removePunct remove punctuation if \code{TRUE}
#' @param lower convert text to lower case \code{TRUE}
#' @param twitter if \code{TRUE}, do not remove \code{@@} or \code{#}
#' @param additional additional characters to remove (\link[=regex]{regular expression})
#' @param ... additional parameters
#' @return A character vector equal in length to the original texts, after cleaning.
#' @examples
#' clean("This is 1 sentence with 1.9 numbers in it, and one comma.", removeDigits=FALSE)
#' clean("This is 1 sentence with 1.9 numbers in it, and one comma.", lower=FALSE)
#' clean("The \"economy\" is [worth] approx. $1.2 trillion.")
#' clean("The \"economy\" is {worth} approx. $1.2 trillion.", additional="[$]")
#' clean("We are his Beliebers, and him is #ourjustin @@justinbieber we love u", twitter=TRUE)
#' clean("Collocations can be represented as inheritance_tax using the _ character.")
#' 
#' # for a vector of texts
#' clean(c("This is 1 sentence with 1.9 numbers in it, and one comma.", 
#'         "$1.2 billion was spent on text analysis in 2014."))
#' @export
clean <- function(x, ...) {
    UseMethod("clean")
}



#' @rdname clean
#' @export
clean.character <- function(x, removeDigits=TRUE, removePunct=TRUE, lower=TRUE, 
                            additional=NULL, twitter=FALSE, ...) {
    if (!(removeDigits | removePunct | lower) & is.null(additional)) {
        warning("  clean: text unchanged")
    }
    return(sapply(x, cleanSingle, removeDigits=removeDigits, removePunct=removePunct, 
                  lower=lower, additional=additional, twitter=twitter,
                  USE.NAMES=FALSE))
}



#' @rdname clean
#' @export
clean.corpus <- function(x, removeDigits=TRUE, removePunct=TRUE, lower=TRUE, 
                         additional=NULL, twitter=FALSE, ...) {
    clean(texts(x), removeDigits=removeDigits, removePunct=removePunct, lower=lower, 
          additional=additional, ...)
}

#' stem words
#' 
#' Apply a stemmer to words.  This is a wrapper to \link[SnowballC]{wordStem} 
#' designed to allow this function to be called without loading the entire 
#' \pkg{SnowballC} package.  \link[SnowballC]{wordStem}  uses Dr. Martin 
#' Porter's stemming algorithm and the C libstemmer library generated by 
#' Snowball.
#' @param words a character vector of words whose stems are to be extracted.
#' @param language the name of a recognized language, as returned by 
#'   getStemLanguages, or a two- or three-letter ISO-639 code corresponding to 
#'   one of these languages (see references for the list of codes)
#' @return A character vector with as many elements as there are in the input
#'   vector with the corresponding elements being the stem of the word. Elements
#'   of the vector are converted to UTF-8 encoding before the stemming is
#'   performed, and the returned elements are marked as such when they contain
#'   non-ASCII characters.
#' @seealso \link[SnowballC]{wordStem}; \url{http://snowball.tartarus.org/}.
#' @export
#' @examples
#' # Simple example
#' wordstem(c("win", "winning", "winner"))
wordstem <- function(words, language = "porter") {
    SnowballC::wordStem(words, language)
}
