# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ngramcpp <- function(words, n, skip, delim) {
    .Call('quanteda_ngramcpp', PACKAGE = 'quanteda', words, n, skip, delim)
}

skipgramcpp <- function(words, n, skip, delim) {
    .Call('quanteda_skipgramcpp', PACKAGE = 'quanteda', words, n, skip, delim)
}

ngramcppl <- function(x, n, skip, delim) {
    .Call('quanteda_ngramcppl', PACKAGE = 'quanteda', x, n, skip, delim)
}

skipgramcppl <- function(x, n, skip, delim) {
    .Call('quanteda_skipgramcppl', PACKAGE = 'quanteda', x, n, skip, delim)
}

wordfishcpp <- function(wfm, dir, priors, tol) {
    .Call('quanteda_wordfishcpp', PACKAGE = 'quanteda', wfm, dir, priors, tol)
}

