# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qatd_ManhattanPara_cpp <- function(A, margin = 1L) {
    .Call('quanteda_qatd_ManhattanPara_cpp', PACKAGE = 'quanteda', A, margin)
}

qatd_ManhattanPara_cpp2 <- function(A, B, margin = 1L) {
    .Call('quanteda_qatd_ManhattanPara_cpp2', PACKAGE = 'quanteda', A, B, margin)
}

qatd_MaximumPara_cpp <- function(A, margin = 1L) {
    .Call('quanteda_qatd_MaximumPara_cpp', PACKAGE = 'quanteda', A, margin)
}

qatd_MaximumPara_cpp2 <- function(A, B, margin = 1L) {
    .Call('quanteda_qatd_MaximumPara_cpp2', PACKAGE = 'quanteda', A, B, margin)
}

qatd_CanberraPara_cpp <- function(A, margin = 1L) {
    .Call('quanteda_qatd_CanberraPara_cpp', PACKAGE = 'quanteda', A, margin)
}

qatd_CanberraPara_cpp2 <- function(A, B, margin = 1L) {
    .Call('quanteda_qatd_CanberraPara_cpp2', PACKAGE = 'quanteda', A, B, margin)
}

qatd_MinkowskiPara_cpp <- function(A, margin = 1L, p = 2) {
    .Call('quanteda_qatd_MinkowskiPara_cpp', PACKAGE = 'quanteda', A, margin, p)
}

qatd_MinkowskiPara_cpp2 <- function(A, B, margin = 1L, p = 2) {
    .Call('quanteda_qatd_MinkowskiPara_cpp2', PACKAGE = 'quanteda', A, B, margin, p)
}

qatd_cpp_fcm <- function(texts_, n_types, count, window, weights, ordered, tri, nvec) {
    .Call('quanteda_qatd_cpp_fcm', PACKAGE = 'quanteda', texts_, n_types, count, window, weights, ordered, tri, nvec)
}

qatd_cpp_sequences <- function(texts_, words_, count_min, len_max, nested, ordered = FALSE) {
    .Call('quanteda_qatd_cpp_sequences', PACKAGE = 'quanteda', texts_, words_, count_min, len_max, nested, ordered)
}

qatd_cpp_tokens_compound <- function(texts_, comps_, types_, delim_, join) {
    .Call('quanteda_qatd_cpp_tokens_compound', PACKAGE = 'quanteda', texts_, comps_, types_, delim_, join)
}

qatd_cpp_tokens_detect <- function(texts_, words_) {
    .Call('quanteda_qatd_cpp_tokens_detect', PACKAGE = 'quanteda', texts_, words_)
}

qatd_cpp_tokens_lookup <- function(texts_, types_, keys_, ids_, overlap) {
    .Call('quanteda_qatd_cpp_tokens_lookup', PACKAGE = 'quanteda', texts_, types_, keys_, ids_, overlap)
}

qatd_cpp_tokens_match <- function(texts_, types_, words_, ids_, overlap) {
    .Call('quanteda_qatd_cpp_tokens_match', PACKAGE = 'quanteda', texts_, types_, words_, ids_, overlap)
}

qatd_cpp_tokens_ngrams <- function(texts_, types_, delim_, ns_, skips_) {
    .Call('quanteda_qatd_cpp_tokens_ngrams', PACKAGE = 'quanteda', texts_, types_, delim_, ns_, skips_)
}

qatd_cpp_tokens_recompile <- function(texts_, types_) {
    .Call('quanteda_qatd_cpp_tokens_recompile', PACKAGE = 'quanteda', texts_, types_)
}

qatd_cpp_tokens_replace <- function(texts_, types_, words_, ids_) {
    .Call('quanteda_qatd_cpp_tokens_replace', PACKAGE = 'quanteda', texts_, types_, words_, ids_)
}

qatd_cpp_tokens_select <- function(texts_, types_, words_, mode, padding) {
    .Call('quanteda_qatd_cpp_tokens_select', PACKAGE = 'quanteda', texts_, types_, words_, mode, padding)
}

qatd_cpp_chars_remove <- function(input_, char_remove) {
    .Call('quanteda_qatd_cpp_chars_remove', PACKAGE = 'quanteda', input_, char_remove)
}

wordfishcpp <- function(wfm, dir, priors, tol, disp, dispfloor) {
    .Call('quanteda_wordfishcpp', PACKAGE = 'quanteda', wfm, dir, priors, tol, disp, dispfloor)
}

wordfish_cpp <- function(wfm, dirvec, priorvec, tolvec, disptype, dispmin, residual_floor) {
    .Call('quanteda_wordfish_cpp', PACKAGE = 'quanteda', wfm, dirvec, priorvec, tolvec, disptype, dispmin, residual_floor)
}

